config/routes.rb
PocBank::Application.routes.draw do
  devise_for :users
  root to: 'home#index'
  get 'about', :to => "home#about", :as => :about
  get 'partner', :to => "home#partner", :as => :partner

  namespace :admin do
    root to: 'dashboards#show'
    resource :dashboard, :only => [:show]
    resources :users
    resources :credits
    resources :debits
    resources :providers
    resources :categories
    resources :user_types
  end

  resources :credits, :only => [:index, :show] do
    collection do
      get 'providers/:id' => "providers#credit_show", :as => :provider
    end
    get 'redirect'
    post 'shortlist', :to => "credits#add_to_shortlist"
    delete 'shortlist', :to => "credits#remove_from_shortlist"
  end
  resources :debits, :only => [:index, :show] do
    collection do
      get 'providers/:id' => "providers#debit_show", :as => :provider
    end
    get 'redirect'
    post 'shortlist', :to => "debits#add_to_shortlist"
    delete 'shortlist', :to => "debits#remove_from_shortlist"
  end

  get 'providers/:id/redirect' => "providers#redirect", :as => :provider_redirect

  resources :locations do
    collection { post :import}
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  extend Enumerize
  enumerize :role, in: [:admin, :user]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :province

  validates :province, :role, :presence => true

  def self.query(query)
    where("email LIKE ?", "%#{query}%")
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ::AdminController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, :notice => "User was successfully created."
    else
      render :action => :new
    end
  end

  def index
    respond_to do |format|
      format.html { }
      format.json do 
        if params[:query] and !params[:query].blank?
          @users = User.query(params[:query]).paginate(:page => params[:page], :per_page => params[:per_page] || 30)
        else
          @users = User.paginate(:page => params[:page], :per_page => params[:per_page] || 30)
        end
      end
    end
  end

  def edit
    @user = User.find(params[:id])
    render :action => :new
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end

  def update
    @user = User.find(params[:id])
    up = user_params
    up.delete(:password_confirmation) if user_params[:password].blank?
    up.delete(:password) if user_params[:password].blank?

    if @user.update_attributes(up)
      redirect_to admin_users_path, :notice => "User was successfully updated."
    else
      render :action => :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :name, :role, :password, :password_confirmation, :avatar, :phone, :province_id) 
  end
end

app/views/admin/users/_form.html.haml
%section.panel
  %header.panel-heading
    User
  .panel-body
    .form
      = simple_form_for [:admin, @user], :html => { :class => "form-horizontal tasi-form" } do |f|
        = f.input :email
        = f.input :password
        = f.input :password_confirmation
        = f.input :name
        = f.input :phone
        = f.association :province, :include_blank => false
        = f.input :avatar
        = f.input :role, :include_blank => false
        = f.button :submit, :class => "btn-danger"

app/views/admin/users/index.html.haml
.row
  .col-lg-12
    #datatable.adv-table{ :data => { :count => User.count } }

.row
  .col-lg-12
    = link_to "Create User", new_admin_user_path, :class => "btn btn-primary"

app/views/admin/users/new.html.haml
.row
  .col-lg-12
    = render "form"