config/routes.rb
PocBank::Application.routes.draw do
  devise_for :users
  root to: 'home#index'
  get 'about', :to => "home#about", :as => :about
  get 'partner', :to => "home#partner", :as => :partner

  namespace :admin do
    root to: 'dashboards#show'
    resource :dashboard, :only => [:show]
    resources :users
    resources :credits
    resources :debits
    resources :providers
    resources :categories
    resources :user_types
  end

  resources :credits, :only => [:index, :show] do
    collection do
      get 'providers/:id' => "providers#credit_show", :as => :provider
    end
    get 'redirect'
    post 'shortlist', :to => "credits#add_to_shortlist"
    delete 'shortlist', :to => "credits#remove_from_shortlist"
  end
  resources :debits, :only => [:index, :show] do
    collection do
      get 'providers/:id' => "providers#debit_show", :as => :provider
    end
    get 'redirect'
    post 'shortlist', :to => "debits#add_to_shortlist"
    delete 'shortlist', :to => "debits#remove_from_shortlist"
  end

  get 'providers/:id/redirect' => "providers#redirect", :as => :provider_redirect

  resources :locations do
    collection { post :import}
  end
end

app/models/credit.rb
class Credit < ActiveRecord::Base
  extend Enumerize
  acts_as_product

  validates :name, :image, :link, :primary_card_annual_fee, :currency_exchange_fee, :presence => true

  validates :cash_back_rate, :finance_charge_per_year, :advance_fee_at_ATM,
    :interest_free_day, :expiry_period, :cash_advance_fee, :numericality => true, :allow_nil => true

  enumerize :brand, :in => [:visa, :master, :american_express, :jcb, :unionpay]

  def self.query(query)
    joins(:product).where("products.name ~~* ?", "%#{query}%")
  end
end

app/controllers/admin/credits_controller.rb
class Admin::CreditsController < ::AdminController
  def new
    @credit = Credit.new
  end

  def create
    @credit = Credit.new(credit_params)
    if @credit.save
      redirect_to admin_credits_path, :notice => "Credit was successfully created."
    else
      render :action => :new
    end
  end

  def index
    respond_to do |format|
      format.html { }
      format.json do 
        if params[:query] and !params[:query].blank?
          @credits = Credit.joins(:product).order("products.name asc").query(params[:query]).paginate(:page => params[:page], :per_page => params[:per_page] || 30)
        else
          @credits = Credit.joins(:product).order("products.name asc").paginate(:page => params[:page], :per_page => params[:per_page] || 30)
        end
      end
    end
  end

  def edit
    @credit = Credit.find(params[:id])
    render :action => :new
  end

  def update
    @credit = Credit.find(params[:id])

    if @credit.update_attributes(credit_params)
      redirect_to admin_credits_path, :notice => "Credit was successfully updated."
    else
      render :action => :new
    end
  end

  def destroy
    @credit = Credit.find(params[:id])
    @credit.destroy
  end

  private
  def credit_params
    params.require(:credit).permit(:name, :image, :link, :provider_id, :recommended, :has_promotion, :description,
        :primary_card_annual_fee, :sub_card_annual_fee, :issuance_fee, :domestic_internal_cash_withdrawal_fee, 
        :domestic_internal_cash_withdrawal_fee_description, :domestic_external_cash_withdrawal_fee,
        :domestic_external_cash_withdrawal_fee_description, :issuance_condition, :reward_point, :reward_card,
        :cash_back_rate, :finance_charge_per_year, :advance_fee_at_ATM, :interest_free_day, :credit_limit, :expiry_period,
        :cash_back_rate_description, :late_charge, :cash_advance_fee, :currency_exchange_fee, :currency_exchange_fee_desc, :brand, :card_rank)
  end
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  def index
    return if search_provider { |id| provider_credits_path(id, :q => params[:q]) }
    @q = Credit.search(params[:q])

    if params[:q]
      @q.product_recommended_eq = true if (params[:q][:credit_features] == "recommended")
      @q.product_has_promotion_eq = true if (params[:q][:credit_features] == "promotion")
      @q.product_primary_card_annual_fee_eq = 0 if (params[:q][:credit_features] == "primary_card_annual_fee")
      @q.product_currency_exchange_fee_lt = 0.025 if (params[:q][:credit_features] == "currency_exchange_fee")
      @q.reward_card_eq = true if (params[:q][:credit_features] == "reward_card")
    end

    #sort
    if @q.sorts.empty?
      if @q.product_currency_exchange_fee_lt
        @q.sorts = 'product_currency_exchange_fee asc'
      else
        @q.sorts = 'product_name asc'
      end
    end

    @credit_shortlist = Credit.where(:id => (session[:credit_shortlist] || []))
    @credits_count = @q.result.count
    @credits = @q.result.paginate(:page => params[:page], :per_page => 15)
  end

  def show

  end

  def redirect
    @product = Credit.find(params[:credit_id])

    @redirect_to = @product.link

    render "shared/product_redirect", :layout => "layouts/redirect"
  end

  def add_to_shortlist
    @credit = Credit.find(params[:credit_id])
    session[:credit_shortlist] ||= []
    session[:credit_shortlist] << @credit.id unless session[:credit_shortlist].include?(@credit.id)
    head :no_content
  end

  def remove_from_shortlist
    @credit = Credit.find(params[:credit_id])

    session[:credit_shortlist] ||= []
    session[:credit_shortlist].delete @credit.id
    head :no_content
  end

end

app/views/admin/credits/_form.html.haml
%section.panel
  %header.panel-heading
    Thẻ Tín Dụng
  .panel-body
    .form
      = simple_form_for [:admin, @credit], :html => { :class => "form-horizontal tasi-form" } do |f|
        = f.input :name, :as => :text
        = f.input :image
        = f.input :link
        = f.input :provider_id, :label => I18n.t(:provider, :scope => [:activerecord, :attributes, :product]), 
          :as => :select, :collection => Provider.order(:name).map { |p| [p.name, p.id] }, :include_blank => false
        = f.input :brand, :include_blank => false
        = f.input :recommended, :as => :boolean
        = f.input :has_promotion, :as => :boolean
        = f.input :description, :as => :text
        = f.input :primary_card_annual_fee
        = f.input :sub_card_annual_fee
        = f.input :issuance_fee
        = f.input :domestic_internal_cash_withdrawal_fee
        = f.input :domestic_internal_cash_withdrawal_fee_description, :as => :text
        = f.input :domestic_external_cash_withdrawal_fee
        = f.input :domestic_external_cash_withdrawal_fee_description, :as => :text
        = f.input :issuance_condition, :as => :text
        = f.input :reward_point, :as => :text
        = f.input :reward_card
        = f.input :cash_back_rate_description, :as => :text
        = f.input :finance_charge_per_year
        = f.input :advance_fee_at_ATM
        = f.input :interest_free_day
        = f.input :credit_limit
        = f.input :expiry_period
        = f.input :late_charge
        = f.input :cash_advance_fee
        = f.input :currency_exchange_fee
        = f.input :currency_exchange_fee_desc, :as => :text
        = f.input :card_rank,
          :collection => Product.card_rank.values.map { |c| [I18n.t(c, :scope => [:enum, :product, :card_rank]), c] },
          :include_blank => false

        = f.button :submit, :class => "btn-danger"

app/views/admin/credits/index.html.haml
.row
  .col-lg-12
    #datatable.adv-table{ :data => { :count => Credit.count } }

.row
  .col-lg-12
    = link_to "Create Credit", new_admin_credit_path, :class => "btn btn-primary"

app/views/admin/credits/new.html.haml
.row
  .col-lg-12
    = render "form"